/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AppRouteImport } from './routes/_app.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as AppIndexRouteImport } from './routes/_app/index.tsx'
import { Route as AppSettingsRouteImport } from './routes/_app/settings.tsx'
import { Route as AppChatSkeyRouteImport } from './routes/_app/chat/$skey.tsx'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index.tsx'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys.tsx'
import { Route as AppSettingsPluginsRouteImport } from './routes/_app/settings/plugins.tsx'
import { Route as AppSettingsSyncRouteImport } from './routes/_app/settings/sync.tsx'
import { Route as SharedOwnerDidSkeyRouteImport } from './routes/shared/$ownerDid/$skey.tsx'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSkeyRoute = AppChatSkeyRouteImport.update({
  id: '/chat/$skey',
  path: '/chat/$skey',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSyncRoute = AppSettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppSettingsRoute,
} as any)
const SharedOwnerDidSkeyRoute = SharedOwnerDidSkeyRouteImport.update({
  id: '/shared/$ownerDid/$skey',
  path: '/shared/$ownerDid/$skey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/chat/$skey': typeof AppChatSkeyRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/chat/$skey': typeof AppChatSkeyRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$skey': typeof AppChatSkeyRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/plugins': typeof AppSettingsPluginsRoute
  '/_app/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/chat/$skey'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/chat/$skey'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/'
    | '/_app/chat/$skey'
    | '/_app/settings/api-keys'
    | '/_app/settings/plugins'
    | '/_app/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SharedOwnerDidSkeyRoute: typeof SharedOwnerDidSkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$skey': {
      id: '/_app/chat/$skey'
      path: '/chat/$skey'
      fullPath: '/chat/$skey'
      preLoaderRoute: typeof AppChatSkeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/plugins': {
      id: '/_app/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/sync': {
      id: '/_app/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AppSettingsSyncRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/shared/$ownerDid/$skey': {
      id: '/shared/$ownerDid/$skey'
      path: '/shared/$ownerDid/$skey'
      fullPath: '/shared/$ownerDid/$skey'
      preLoaderRoute: typeof SharedOwnerDidSkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRoute
  AppSettingsSyncRoute: typeof AppSettingsSyncRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRoute,
  AppSettingsSyncRoute: AppSettingsSyncRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatSkeyRoute: typeof AppChatSkeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatSkeyRoute: AppChatSkeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SharedOwnerDidSkeyRoute: SharedOwnerDidSkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
