/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AppRouteImport } from './routes/_app.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as AppChatsRouteImport } from './routes/_app/_chats.tsx'
import { Route as AppAdminRouteImport } from './routes/_app/admin.tsx'
import { Route as AppSettingsRouteImport } from './routes/_app/settings.tsx'
import { Route as AppChatsIndexRouteImport } from './routes/_app/_chats/index.tsx'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index.tsx'
import { Route as AppAdminAccessRouteImport } from './routes/_app/admin/access.tsx'
import { Route as AppAdminApiKeysRouteImport } from './routes/_app/admin/api-keys.tsx'
import { Route as AppAdminCronRouteImport } from './routes/_app/admin/cron.tsx'
import { Route as AppAdminGeneralRouteImport } from './routes/_app/admin/general.tsx'
import { Route as AppAdminModelsRouteImport } from './routes/_app/admin/models.tsx'
import { Route as AppAdminSyncRouteImport } from './routes/_app/admin/sync.tsx'
import { Route as AppAdminTurnsRouteImport } from './routes/_app/admin/turns.tsx'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users.tsx'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index.tsx'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys.tsx'
import { Route as AppSettingsPluginsRouteImport } from './routes/_app/settings/plugins.tsx'
import { Route as AppSettingsSyncRouteImport } from './routes/_app/settings/sync.tsx'
import { Route as SharedOwnerDidSkeyRouteImport } from './routes/shared/$ownerDid/$skey.tsx'
import { Route as AppChatsChatSkeyRouteImport } from './routes/_app/_chats/chat/$skey.tsx'
import { Route as AppAdminPluginsIndexRouteImport } from './routes/_app/admin/plugins/index.tsx'
import { Route as AppAdminPluginsNewRouteImport } from './routes/_app/admin/plugins/new.tsx'
import { Route as AppAdminRolesIndexRouteImport } from './routes/_app/admin/roles/index.tsx'
import { Route as AppAdminRolesNameRouteImport } from './routes/_app/admin/roles/$name.tsx'
import { Route as AppAdminPluginsIdIndexRouteImport } from './routes/_app/admin/plugins/$id/index.tsx'
import { Route as AppAdminPluginsIdModelRouteImport } from './routes/_app/admin/plugins/$id/model.tsx'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/_chats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAccessRoute = AppAdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApiKeysRoute = AppAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCronRoute = AppAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGeneralRoute = AppAdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModelsRoute = AppAdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSyncRoute = AppAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTurnsRoute = AppAdminTurnsRouteImport.update({
  id: '/turns',
  path: '/turns',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSyncRoute = AppSettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppSettingsRoute,
} as any)
const SharedOwnerDidSkeyRoute = SharedOwnerDidSkeyRouteImport.update({
  id: '/shared/$ownerDid/$skey',
  path: '/shared/$ownerDid/$skey',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsChatSkeyRoute = AppChatsChatSkeyRouteImport.update({
  id: '/chat/$skey',
  path: '/chat/$skey',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppAdminPluginsIndexRoute = AppAdminPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPluginsNewRoute = AppAdminPluginsNewRouteImport.update({
  id: '/plugins/new',
  path: '/plugins/new',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesIndexRoute = AppAdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesNameRoute = AppAdminRolesNameRouteImport.update({
  id: '/roles/$name',
  path: '/roles/$name',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPluginsIdIndexRoute = AppAdminPluginsIdIndexRouteImport.update({
  id: '/plugins/$id/',
  path: '/plugins/$id/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPluginsIdModelRoute = AppAdminPluginsIdModelRouteImport.update({
  id: '/plugins/$id/model',
  path: '/plugins/$id/model',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppChatsIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/admin/access': typeof AppAdminAccessRoute
  '/admin/api-keys': typeof AppAdminApiKeysRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/general': typeof AppAdminGeneralRoute
  '/admin/models': typeof AppAdminModelsRoute
  '/admin/sync': typeof AppAdminSyncRoute
  '/admin/turns': typeof AppAdminTurnsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/admin/': typeof AppAdminIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/chat/$skey': typeof AppChatsChatSkeyRoute
  '/admin/plugins/new': typeof AppAdminPluginsNewRoute
  '/admin/roles/$name': typeof AppAdminRolesNameRoute
  '/admin/plugins/': typeof AppAdminPluginsIndexRoute
  '/admin/roles/': typeof AppAdminRolesIndexRoute
  '/admin/plugins/$id/model': typeof AppAdminPluginsIdModelRoute
  '/admin/plugins/$id/': typeof AppAdminPluginsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppChatsIndexRoute
  '/login': typeof LoginRoute
  '/admin/access': typeof AppAdminAccessRoute
  '/admin/api-keys': typeof AppAdminApiKeysRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/general': typeof AppAdminGeneralRoute
  '/admin/models': typeof AppAdminModelsRoute
  '/admin/sync': typeof AppAdminSyncRoute
  '/admin/turns': typeof AppAdminTurnsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/admin': typeof AppAdminIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/chat/$skey': typeof AppChatsChatSkeyRoute
  '/admin/plugins/new': typeof AppAdminPluginsNewRoute
  '/admin/roles/$name': typeof AppAdminRolesNameRoute
  '/admin/plugins': typeof AppAdminPluginsIndexRoute
  '/admin/roles': typeof AppAdminRolesIndexRoute
  '/admin/plugins/$id/model': typeof AppAdminPluginsIdModelRoute
  '/admin/plugins/$id': typeof AppAdminPluginsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_chats': typeof AppChatsRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/admin/access': typeof AppAdminAccessRoute
  '/_app/admin/api-keys': typeof AppAdminApiKeysRoute
  '/_app/admin/cron': typeof AppAdminCronRoute
  '/_app/admin/general': typeof AppAdminGeneralRoute
  '/_app/admin/models': typeof AppAdminModelsRoute
  '/_app/admin/sync': typeof AppAdminSyncRoute
  '/_app/admin/turns': typeof AppAdminTurnsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/plugins': typeof AppSettingsPluginsRoute
  '/_app/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/_app/_chats/': typeof AppChatsIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/_chats/chat/$skey': typeof AppChatsChatSkeyRoute
  '/_app/admin/plugins/new': typeof AppAdminPluginsNewRoute
  '/_app/admin/roles/$name': typeof AppAdminRolesNameRoute
  '/_app/admin/plugins/': typeof AppAdminPluginsIndexRoute
  '/_app/admin/roles/': typeof AppAdminRolesIndexRoute
  '/_app/admin/plugins/$id/model': typeof AppAdminPluginsIdModelRoute
  '/_app/admin/plugins/$id/': typeof AppAdminPluginsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/settings'
    | '/admin/access'
    | '/admin/api-keys'
    | '/admin/cron'
    | '/admin/general'
    | '/admin/models'
    | '/admin/sync'
    | '/admin/turns'
    | '/admin/users'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/admin/'
    | '/settings/'
    | '/chat/$skey'
    | '/admin/plugins/new'
    | '/admin/roles/$name'
    | '/admin/plugins/'
    | '/admin/roles/'
    | '/admin/plugins/$id/model'
    | '/admin/plugins/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/access'
    | '/admin/api-keys'
    | '/admin/cron'
    | '/admin/general'
    | '/admin/models'
    | '/admin/sync'
    | '/admin/turns'
    | '/admin/users'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/admin'
    | '/settings'
    | '/chat/$skey'
    | '/admin/plugins/new'
    | '/admin/roles/$name'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/plugins/$id/model'
    | '/admin/plugins/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_chats'
    | '/_app/admin'
    | '/_app/settings'
    | '/_app/admin/access'
    | '/_app/admin/api-keys'
    | '/_app/admin/cron'
    | '/_app/admin/general'
    | '/_app/admin/models'
    | '/_app/admin/sync'
    | '/_app/admin/turns'
    | '/_app/admin/users'
    | '/_app/settings/api-keys'
    | '/_app/settings/plugins'
    | '/_app/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/_app/_chats/'
    | '/_app/admin/'
    | '/_app/settings/'
    | '/_app/_chats/chat/$skey'
    | '/_app/admin/plugins/new'
    | '/_app/admin/roles/$name'
    | '/_app/admin/plugins/'
    | '/_app/admin/roles/'
    | '/_app/admin/plugins/$id/model'
    | '/_app/admin/plugins/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SharedOwnerDidSkeyRoute: typeof SharedOwnerDidSkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_chats': {
      id: '/_app/_chats'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_chats/': {
      id: '/_app/_chats/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/access': {
      id: '/_app/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AppAdminAccessRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/api-keys': {
      id: '/_app/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AppAdminApiKeysRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/cron': {
      id: '/_app/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AppAdminCronRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/general': {
      id: '/_app/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AppAdminGeneralRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/models': {
      id: '/_app/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AppAdminModelsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/sync': {
      id: '/_app/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AppAdminSyncRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/turns': {
      id: '/_app/admin/turns'
      path: '/turns'
      fullPath: '/admin/turns'
      preLoaderRoute: typeof AppAdminTurnsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/plugins': {
      id: '/_app/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/sync': {
      id: '/_app/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AppSettingsSyncRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/shared/$ownerDid/$skey': {
      id: '/shared/$ownerDid/$skey'
      path: '/shared/$ownerDid/$skey'
      fullPath: '/shared/$ownerDid/$skey'
      preLoaderRoute: typeof SharedOwnerDidSkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_chats/chat/$skey': {
      id: '/_app/_chats/chat/$skey'
      path: '/chat/$skey'
      fullPath: '/chat/$skey'
      preLoaderRoute: typeof AppChatsChatSkeyRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/admin/plugins/': {
      id: '/_app/admin/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AppAdminPluginsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/plugins/new': {
      id: '/_app/admin/plugins/new'
      path: '/plugins/new'
      fullPath: '/admin/plugins/new'
      preLoaderRoute: typeof AppAdminPluginsNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles/': {
      id: '/_app/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AppAdminRolesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles/$name': {
      id: '/_app/admin/roles/$name'
      path: '/roles/$name'
      fullPath: '/admin/roles/$name'
      preLoaderRoute: typeof AppAdminRolesNameRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/plugins/$id/': {
      id: '/_app/admin/plugins/$id/'
      path: '/plugins/$id'
      fullPath: '/admin/plugins/$id/'
      preLoaderRoute: typeof AppAdminPluginsIdIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/plugins/$id/model': {
      id: '/_app/admin/plugins/$id/model'
      path: '/plugins/$id/model'
      fullPath: '/admin/plugins/$id/model'
      preLoaderRoute: typeof AppAdminPluginsIdModelRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppChatsRouteChildren {
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppChatsChatSkeyRoute: typeof AppChatsChatSkeyRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppChatsChatSkeyRoute: AppChatsChatSkeyRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAccessRoute: typeof AppAdminAccessRoute
  AppAdminApiKeysRoute: typeof AppAdminApiKeysRoute
  AppAdminCronRoute: typeof AppAdminCronRoute
  AppAdminGeneralRoute: typeof AppAdminGeneralRoute
  AppAdminModelsRoute: typeof AppAdminModelsRoute
  AppAdminSyncRoute: typeof AppAdminSyncRoute
  AppAdminTurnsRoute: typeof AppAdminTurnsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminPluginsNewRoute: typeof AppAdminPluginsNewRoute
  AppAdminRolesNameRoute: typeof AppAdminRolesNameRoute
  AppAdminPluginsIndexRoute: typeof AppAdminPluginsIndexRoute
  AppAdminRolesIndexRoute: typeof AppAdminRolesIndexRoute
  AppAdminPluginsIdModelRoute: typeof AppAdminPluginsIdModelRoute
  AppAdminPluginsIdIndexRoute: typeof AppAdminPluginsIdIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAccessRoute: AppAdminAccessRoute,
  AppAdminApiKeysRoute: AppAdminApiKeysRoute,
  AppAdminCronRoute: AppAdminCronRoute,
  AppAdminGeneralRoute: AppAdminGeneralRoute,
  AppAdminModelsRoute: AppAdminModelsRoute,
  AppAdminSyncRoute: AppAdminSyncRoute,
  AppAdminTurnsRoute: AppAdminTurnsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminPluginsNewRoute: AppAdminPluginsNewRoute,
  AppAdminRolesNameRoute: AppAdminRolesNameRoute,
  AppAdminPluginsIndexRoute: AppAdminPluginsIndexRoute,
  AppAdminRolesIndexRoute: AppAdminRolesIndexRoute,
  AppAdminPluginsIdModelRoute: AppAdminPluginsIdModelRoute,
  AppAdminPluginsIdIndexRoute: AppAdminPluginsIdIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRoute
  AppSettingsSyncRoute: typeof AppSettingsSyncRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRoute,
  AppSettingsSyncRoute: AppSettingsSyncRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SharedOwnerDidSkeyRoute: SharedOwnerDidSkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
