/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AppRouteImport } from './routes/_app.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as AppChatsRouteImport } from './routes/_app/_chats.tsx'
import { Route as AppSettingsRouteImport } from './routes/_app/settings.tsx'
import { Route as AppChatsIndexRouteImport } from './routes/_app/_chats/index.tsx'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index.tsx'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys.tsx'
import { Route as AppSettingsPluginsRouteImport } from './routes/_app/settings/plugins.tsx'
import { Route as AppSettingsSyncRouteImport } from './routes/_app/settings/sync.tsx'
import { Route as SharedOwnerDidSkeyRouteImport } from './routes/shared/$ownerDid/$skey.tsx'
import { Route as AppChatsChatSkeyRouteImport } from './routes/_app/_chats/chat/$skey.tsx'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/_chats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSyncRoute = AppSettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppSettingsRoute,
} as any)
const SharedOwnerDidSkeyRoute = SharedOwnerDidSkeyRouteImport.update({
  id: '/shared/$ownerDid/$skey',
  path: '/shared/$ownerDid/$skey',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsChatSkeyRoute = AppChatsChatSkeyRouteImport.update({
  id: '/chat/$skey',
  path: '/chat/$skey',
  getParentRoute: () => AppChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppChatsIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/chat/$skey': typeof AppChatsChatSkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof AppChatsIndexRoute
  '/login': typeof LoginRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/settings': typeof AppSettingsIndexRoute
  '/chat/$skey': typeof AppChatsChatSkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_chats': typeof AppChatsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/plugins': typeof AppSettingsPluginsRoute
  '/_app/settings/sync': typeof AppSettingsSyncRoute
  '/shared/$ownerDid/$skey': typeof SharedOwnerDidSkeyRoute
  '/_app/_chats/': typeof AppChatsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/_chats/chat/$skey': typeof AppChatsChatSkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/settings/'
    | '/chat/$skey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings/api-keys'
    | '/settings/plugins'
    | '/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/settings'
    | '/chat/$skey'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_chats'
    | '/_app/settings'
    | '/_app/settings/api-keys'
    | '/_app/settings/plugins'
    | '/_app/settings/sync'
    | '/shared/$ownerDid/$skey'
    | '/_app/_chats/'
    | '/_app/settings/'
    | '/_app/_chats/chat/$skey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SharedOwnerDidSkeyRoute: typeof SharedOwnerDidSkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_chats': {
      id: '/_app/_chats'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_chats/': {
      id: '/_app/_chats/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/plugins': {
      id: '/_app/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/sync': {
      id: '/_app/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AppSettingsSyncRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/shared/$ownerDid/$skey': {
      id: '/shared/$ownerDid/$skey'
      path: '/shared/$ownerDid/$skey'
      fullPath: '/shared/$ownerDid/$skey'
      preLoaderRoute: typeof SharedOwnerDidSkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_chats/chat/$skey': {
      id: '/_app/_chats/chat/$skey'
      path: '/chat/$skey'
      fullPath: '/chat/$skey'
      preLoaderRoute: typeof AppChatsChatSkeyRouteImport
      parentRoute: typeof AppChatsRoute
    }
  }
}

interface AppChatsRouteChildren {
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppChatsChatSkeyRoute: typeof AppChatsChatSkeyRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppChatsChatSkeyRoute: AppChatsChatSkeyRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRoute
  AppSettingsSyncRoute: typeof AppSettingsSyncRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRoute,
  AppSettingsSyncRoute: AppSettingsSyncRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SharedOwnerDidSkeyRoute: SharedOwnerDidSkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
